export { ConversationCanvas } from './diagram/ConversationCanvas'
export { DetailPanel } from './diagram/DetailPanel'
export { MessageComposer } from './diagram/MessageComposer'
export { SessionSidebar } from './diagram/SessionSidebar'
export { DiagramShell } from './diagram/DiagramShell'
export { ProductRail } from './product-rail/ProductRail'
export type { ProductId } from './product-rail/ProductRail'
