export { ConversationCanvas } from './workspace/ConversationCanvas'
export { DetailPanel } from './workspace/DetailPanel'
export { MessageComposer } from './workspace/MessageComposer'
export { SessionSidebar } from './workspace/SessionSidebar'
export { WorkspaceShell } from './workspace/WorkspaceShell'
