export { GlobalStatusBar } from './status-bar/GlobalStatusBar'
export { WorkspaceCanvas } from './workspace/WorkspaceCanvas'
export { WorkspaceInspector } from './workspace/WorkspaceInspector'
export { WorkspaceShell } from './workspace/WorkspaceShell'
export { WorkspaceSidebar } from './workspace/WorkspaceSidebar'
